const FINISHED_ON_BOARDING = 'finishedOnBoarding';
const COLOR_ACCENT = 0xFFd756ff;
const COLOR_PRIMARY_DARK = 0xFF6900be;
const COLOR_PRIMARY = 0xFFa011f2;
const FACEBOOK_BUTTON_COLOR = 0xFF415893;
const USERS = 'users';
