// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocL-Qp9-GChNR41orq0zRB5ZBSZyiNI8',
    appId: '1:681429977010:web:aabbe97fe8160fabf406ab',
    messagingSenderId: '681429977010',
    projectId: 'instaflutter-production-demos',
    authDomain: 'instaflutter-production-demos.firebaseapp.com',
    storageBucket: 'instaflutter-production-demos.appspot.com',
    measurementId: 'G-Y0811LQNFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFh93J9f1SQWhoFQzfuaMaJRi4GHGn-g',
    appId: '1:681429977010:android:309df57baf2e313ef406ab',
    messagingSenderId: '681429977010',
    projectId: 'instaflutter-production-demos',
    storageBucket: 'instaflutter-production-demos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AbTc8p2KZTE1FuWEK1ScpqRRJD0ki_s',
    appId: '1:681429977010:ios:f40d487361cc0644f406ab',
    messagingSenderId: '681429977010',
    projectId: 'instaflutter-production-demos',
    storageBucket: 'instaflutter-production-demos.appspot.com',
    androidClientId:
        '681429977010-2a9mfnn2m9r8fhvkcq3tbpmfnou9s1ju.apps.googleusercontent.com',
    iosClientId:
        '681429977010-6m62ujpt85sj5hnoe5rk4sm5innv3nq9.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.freeLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9AbTc8p2KZTE1FuWEK1ScpqRRJD0ki_s',
    appId: '1:681429977010:ios:f40d487361cc0644f406ab',
    messagingSenderId: '681429977010',
    projectId: 'instaflutter-production-demos',
    storageBucket: 'instaflutter-production-demos.appspot.com',
    androidClientId:
        '681429977010-2a9mfnn2m9r8fhvkcq3tbpmfnou9s1ju.apps.googleusercontent.com',
    iosClientId:
        '681429977010-6m62ujpt85sj5hnoe5rk4sm5innv3nq9.apps.googleusercontent.com',
    iosBundleId: 'com.instaflutter.freeloginscreen.freeLogin',
  );
}
